DEVICE: "cuda"
SEED: 0
SAVE: TRUE
SAVE_PATH: synlexnorm_finetuning/models

# Model
modeltype: "t5"
pretrained_name: "google/byt5-small"

# Pretraining
DO_PRETRAINING: TRUE


#Pretrain-Train Hyper

## Batch size
PRETRAIN_BATCH_SIZE: 8
TRAIN_BATCH_SIZE: 8
EVAL_BATCH_SIZE: 16
PREDICT_BATCH_SIZE: 16
## Optim
LR: 0.0001
BETAS: 
  - 0.9
  - 0.98
warmup_step: 1000

## Steps
NUM_PRETRAIN_STEP: 5000
show_loss_after_pretrain_steps: 200
save_after_pretrain_steps: 2000

NUM_TRAIN_STEP: 5000
show_loss_after_steps: 200
eval_after_steps: 1000

max_eval_length: 256
## Data path
pretrain_data_path: "/wiki20k_droptypo.csv"
train_path: "/train.csv"
val_path: "/dev.csv"
predict_path: "/dev.csv"

src_max_token_len: 512
trg_max_token_len: 512

## Predict
get_predict_score: TRUE
max_predict_length: 512

